version: '3.9'
services:
  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    working_dir: /var/www/${APP_NAME}
    volumes:
      - ./:/var/www/${APP_NAME}
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - APP_NAME=${APP_NAME}
    links:
      - php
      - postgres
    depends_on:
      - php
      - postgres
    ports:
      - "80:80"
  php:
    container_name: ${APP_NAME}-php
    build:
      context: .docker/php
      dockerfile: Dockerfile
    extra_hosts:
      - "${HOST_DOCKER_INTERNAL}:host-gateway"
    volumes:
      - ./:/var/www/${APP_NAME}
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/z-php.ini
    working_dir: /var/www/${APP_NAME}
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "9000:9000"
  postgres:
    container_name: ${APP_NAME}-postgres
    image: postgres:12
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - ${DB_PORT}:5432
volumes:
  postgres:
    external: true
  redis:
    external: true
